#Define pipeline stages
stages:
    - install
    - build
    - test
    - deploy

#Install Dependencies
install-dependencies:
    stage: install
    image: node:20
    script:
        - echo "Installing backend dependencies..."
        - cd WagInn-Backend && npm install
        - echo "Installing frontend dependencies..."
        - cd ../WagInn-Project && npm install
    cache:
        paths:
        - WagInn_Backend/node_modules/
        - WagInn_Project/node_modules/

# Build frontend
build-frontend:
  stage: build
  image: node:20
  script:
    - cd WagInn-Project
    # Clean install to ensure consistent state
    - rm -rf node_modules package-lock.json
    - npm install #install Angular CLI locally too
    # Create environment files from GitLab variables
    - mkdir -p src/environments
    - |
      cat > src/environments/environment.ts << 'EOF'
      export const environment = {
        production: false,
        apiUrlHostRegister: '$API_URL_HOST_REGISTER',
        apiUrlHostSignIn: '$API_URL_HOST_SIGNIN',
        apiUrlUserRegister: '$API_URL_USER_REGISTER',
        apiUrlUserSignIn: '$API_URL_USER_SIGNIN',
        apiUrlFetchProperty: '$API_URL_FETCH_PROPERTY',
        apiUrlCreateBooking: '$API_URL_CREATE_BOOKING',
        apiUrlGetUserBookings: '$API_URL_GET_USER_BOOKINGS',
        apiUrlGetHostBookings: '$API_URL_GET_HOST_BOOKINGS',
        apiUrlGetBookingByConfirmation: '$API_URL_GET_BOOKING_BY_CONFIRMATION',
        apiUrlCancelBooking: '$API_URL_CANCEL_BOOKING',
        apiUrlGetBookingDetails: '$API_URL_GET_BOOKING_DETAILS',
        apiUrlCheckAvailability: '$API_URL_CHECK_AVAILABILITY',
      };
      EOF
    - |
      cat > src/environments/environment.prod.ts << 'EOF'
      export const environment = {
        production: true,
        apiUrlHostRegister: '$API_URL_HOST_REGISTER',
        apiUrlHostSignIn: '$API_URL_HOST_SIGNIN',
        apiUrlUserRegister: '$API_URL_USER_REGISTER',
        apiUrlUserSignIn: '$API_URL_USER_SIGNIN',
        apiUrlFetchProperty: '$API_URL_FETCH_PROPERTY',
        apiUrlCreateBooking: '$API_URL_CREATE_BOOKING',
        apiUrlGetUserBookings: '$API_URL_GET_USER_BOOKINGS',
        apiUrlGetHostBookings: '$API_URL_GET_HOST_BOOKINGS',
        apiUrlGetBookingByConfirmation: '$API_URL_GET_BOOKING_BY_CONFIRMATION',
        apiUrlCancelBooking: '$API_URL_CANCEL_BOOKING',
        apiUrlGetBookingDetails: '$API_URL_GET_BOOKING_DETAILS',
        apiUrlCheckAvailability: '$API_URL_CHECK_AVAILABILITY',
      };
      EOF
    # Replace placeholders with actual GitLab variables
    - sed -i "s|\$API_URL_HOST_REGISTER|$API_URL_HOST_REGISTER|g" src/environments/environment.ts
    - sed -i "s|\$API_URL_HOST_SIGNIN|$API_URL_HOST_SIGNIN|g" src/environments/environment.ts
    - sed -i "s|\$API_URL_USER_REGISTER|$API_URL_USER_REGISTER|g" src/environments/environment.ts
    - sed -i "s|\$API_URL_USER_SIGNIN|$API_URL_USER_SIGNIN|g" src/environments/environment.ts
    - sed -i "s|\$API_URL_FETCH_PROPERTY|$API_URL_FETCH_PROPERTY|g" src/environments/environment.ts
    - sed -i "s|\$API_URL_CREATE_BOOKING|$API_URL_CREATE_BOOKING|g" src/environments/environment.ts
    - sed -i "s|\$API_URL_GET_USER_BOOKINGS|$API_URL_GET_USER_BOOKINGS|g" src/environments/environment.ts
    - sed -i "s|\$API_URL_GET_HOST_BOOKINGS|$API_URL_GET_HOST_BOOKINGS|g" src/environments/environment.ts
    - sed -i "s|\$API_URL_GET_BOOKING_BY_CONFIRMATION|$API_URL_GET_BOOKING_BY_CONFIRMATION|g" src/environments/environment.ts
    - sed -i "s|\$API_URL_CANCEL_BOOKING|$API_URL_CANCEL_BOOKING|g" src/environments/environment.ts
    - sed -i "s|\$API_URL_GET_BOOKING_DETAILS|$API_URL_GET_BOOKING_DETAILS|g" src/environments/environment.ts
    - sed -i "s|\$API_URL_CHECK_AVAILABILITY|$API_URL_CHECK_AVAILABILITY|g" src/environments/environment.ts
    # Do the same for production environment
    - sed -i "s|\$API_URL_HOST_REGISTER|$API_URL_HOST_REGISTER|g" src/environments/environment.prod.ts
    - sed -i "s|\$API_URL_HOST_SIGNIN|$API_URL_HOST_SIGNIN|g" src/environments/environment.prod.ts
    - sed -i "s|\$API_URL_USER_REGISTER|$API_URL_USER_REGISTER|g" src/environments/environment.prod.ts
    - sed -i "s|\$API_URL_USER_SIGNIN|$API_URL_USER_SIGNIN|g" src/environments/environment.prod.ts
    - sed -i "s|\$API_URL_FETCH_PROPERTY|$API_URL_FETCH_PROPERTY|g" src/environments/environment.prod.ts
    - sed -i "s|\$API_URL_CREATE_BOOKING|$API_URL_CREATE_BOOKING|g" src/environments/environment.prod.ts
    - sed -i "s|\$API_URL_GET_USER_BOOKINGS|$API_URL_GET_USER_BOOKINGS|g" src/environments/environment.prod.ts
    - sed -i "s|\$API_URL_GET_HOST_BOOKINGS|$API_URL_GET_HOST_BOOKINGS|g" src/environments/environment.prod.ts
    - sed -i "s|\$API_URL_GET_BOOKING_BY_CONFIRMATION|$API_URL_GET_BOOKING_BY_CONFIRMATION|g" src/environments/environment.prod.ts
    - sed -i "s|\$API_URL_CANCEL_BOOKING|$API_URL_CANCEL_BOOKING|g" src/environments/environment.prod.ts
    - sed -i "s|\$API_URL_GET_BOOKING_DETAILS|$API_URL_GET_BOOKING_DETAILS|g" src/environments/environment.prod.ts
    - sed -i "s|\$API_URL_CHECK_AVAILABILITY|$API_URL_CHECK_AVAILABILITY|g" src/environments/environment.prod.ts
    # Verify environment files exist
     # Verify environment files exist
    - test -f src/environments/environment.ts || (echo "Environment file missing!" && exit 1)
    - test -f src/environments/environment.prod.ts || (echo "Production environment file missing!" && exit 1)
     # Build with verbose output for debugging
    - npx ng build --verbose
  artifacts:
    paths:
      - WagInn-Project/dist/

# Test backend (runs in parallel with frontend tests)
test-backend:
  stage: test
  image: node:20
  script:
    # - cd WagInn-Backend
    # - npm install
    # - npm test || echo "No backend tests found"
    - echo "Backend tests skipped - no tests configured"

# Test frontend (runs in parallel with backend tests)
test-frontend:
  stage: test
  image: node:20
  script:
    # - cd WagInn-Project
    # - npm install
    # - npm test || echo "No frontend tests found"
    - echo "Frontend tests skipped - no tests configured"

# Deploy to Heroku (only on main branch)
deploy-to-heroku:
  stage: deploy
  image: node:20
  services:
    - docker:dind
  script:
    - echo "Deploying to Heroku..."
    # Install Docker CLI in Node.js container
    - apt-get update && apt-get install -y docker.io
    # Install Heroku CLI
    - curl https://cli-assets.heroku.com/install.sh | sh
    # Authenticate using stdin (this should work)
    - echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com
    # Create Dockerfile
    - |
      cat > Dockerfile << 'EOF'
      FROM nginx:alpine
      COPY WagInn-Project/dist/ /usr/share/nginx/html/
      EXPOSE $PORT
      CMD sed -i -e 's/$PORT/'"$PORT"'/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'
      EOF
    # Build and push directly to Heroku registry
    - docker build -t registry.heroku.com/wag-inn/web .
    - docker push registry.heroku.com/wag-inn/web
    # Release the container
    - export HEROKU_API_KEY=$HEROKU_API_KEY
    - heroku container:release web -a wag-inn
  only:
    - master    #Deploys only when pushed to master