version: "3.8"

services:
  backend:
    command: npm run dev
    environment:
      NODE_ENV: development
    volumes:
      - ./WagInn-Backend:/app
      - /app/node_modules

  frontend:
    environment:
      NODE_ENV: development
    volumes:
      - ./WagInn-Project:/app
      - /app/node_modules
